#!/bin/bash

cd "$(dirname "$0")"
. ./conoha_init
. ./conoha_body

sub_command=

case "$1" in
    init | list | ls | up | rm | ssh)
        sub_command=$1
        shift
        ;;
    -h)
        echo help
        exit 0
        ;;
    *)
        echo unknown command
        exit 1
        ;;
esac

result=0

if [[ $sub_command == init ]]; then
    conoha_init
    result=$?
else
    init
fi

if [[ $sub_command == list || $sub_command == ls ]]; then
    conoha_list
    result=$?

elif [[ $sub_command == up ]]; then
    conoha_up
    result=$?

elif [[ $sub_command == rm ]]; then
    conoha_rm
    result=$?

elif [[ $sub_command == ssh ]]; then
    conoha_ssh
    result=$?

fi

exit "$result"
  

